### ISSUE TITLE
The sample link in the README for the YoutubeVideoPreview element gives a 404

### ISSUE THREAD

**Issue by BorisPocatko** [Kentico/kontent-custom-element-samples#87]
### Brief bug description

The sample link in the README for the YoutubeVideoPreview element gives a 404

https://kentico.github.io/custom-element-samples/YoutubeVideoPreview/youtube.html

**Comment by ChristopherJennings** [comment]
@BorisPocatko this is expected. I'm in the process of updating the readme files and repositories to replace the "hosted" version with Netlify deploy buttons (where applicable). This is to make it easy for people to fork the repo and use their own copy, rather than rely on something we're providing and not intending to support that can change or break at any time. This specifically broke because we recently removed the "compiled" versions of the custom elements from this repository as maintenance is difficult and people shouldn't be relying on these URLs in production.

**Comment by ChristopherJennings** [comment]
I've updated the link to [the new repo](https://github.com/Kentico/kontent-custom-element-youtube-preview) (it originally linked to a fork of the CESG) and added the deploy button. You can deploy there or use the button below:

[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/Kentico/kontent-custom-element-youtube-preview)
